name: Build Ionic Angular App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli@6.16.3

      - name: Build APK
        run: |
          ionic capacitor build android --prod
          cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
